language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: "6"

before_script:
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"

install:
  - npm install

script:
  - . ./.scripts/deploy.sh
